CREATE TABLE PLAYER (
    ID INT PRIMARY KEY,
    FNAME VARCHAR(64) NOT NULL,
    LNAME VARCHAR(64) NOT NULL,
    RESIDENCE VARCHAR(64),
    HEIGHT REAL,
    WEIGHT REAL,
    AGE INT,
    GRIP VARCHAR(64)
);

CREATE TABLE MATCH (
    TIMESTAMP DATETIME PRIMARY KEY
);

CREATE TABLE BALL (
    BRAND VARCHAR(64),
    TIER INT,
    DESIGN VARCHAR(64),
    PRIMARY KEY(BRAND, TIER)
);

CREATE TABLE PADDLE (
    BRAND VARCHAR(64),
    MODEL VARCHAR(64),
    WEIGHT REAL,
    PRIMARY KEY(BRAND, MODEL)
);

CREATE TABLE PADDLE_COLOR (
    BRAND VARCHAR(64) REFERENCES PADDLE,
    MODEL VARCHAR(64) REFERENCES PADDLE,
    COLOR VARCHAR(64),
    PRIMARY KEY(BRAND, MODEL, COLOR)
);

CREATE TABLE GAME (
    GAME_NUM INT,
    TIMESTAMP DATETIME REFERENCES MATCH,
    F_PAD_BRAND VARCHAR(64) REFERENCES PADDLE(BRAND),
    F_PAD_MODEL VARCHAR(64) REFERENCES PADDLE(MODEL),
    S_PAD_BRAND VARCHAR(64) REFERENCES PADDLE(BRAND),
    S_PAD_MODEL VARCHAR(64) REFERENCES PADDLE(MODEL),
    F_PID INT REFERENCES PLAYER(ID) NOT NULL,
    S_PID INT REFERENCES PLAYER(ID) NOT NULL,
    F_EDGE INT,
    S_EDGE INT,
    F_TABLE_SIDE INT,
    F_SCORE INT NOT NULL,
    S_SCORE INT NOT NULL,
    BALL_BRAND VARCHAR(64) REFERENCES BALL(BRAND),
    BALL_TIER INT REFERENCES BALL(TIER),
    PRIMARY KEY(GAME_NUM, TIMESTAMP)
);

CREATE TABLE OWNS (
    PADDLE_BRAND VARCHAR(64) REFERENCES PADDLE(BRAND),
    PADDLE_MODEL VARCHAR(64) REFERENCES PADDLE(MODEL),
    PLAYER_ID int REFERENCES PLAYER(ID),
    PRIMARY KEY(PADDLE_BRAND, PADDLE_MODEL, PLAYER_ID)
);