CREATE TABLE PLAYER (
    ID INT PRIMARY KEY,
    FNAME VARCHAR(64) NOT NULL,
    LNAME VARCHAR(64) NOT NULL,
    RESIDENCE VARCHAR(64),
    HEIGHT REAL,
    WEIGHT REAL,
    AGE INT,
    GRIP VARCHAR(64)
);

CREATE TABLE MATCH (
    TIMESTAMP DATETIME PRIMARY KEY
);

CREATE TABLE BALL (
    BRAND VARCHAR(64),
    TIER INT,
    DESIGN VARCHAR(64),
    PRIMARY KEY(BRAND, TIER)
);

CREATE TABLE PADDLE (
    BRAND VARCHAR(64),
    MODEL VARCHAR(64),
    WEIGHT REAL,
    PRIMARY KEY(BRAND, MODEL)
);

CREATE TABLE PADDLE_COLOR (
    BRAND VARCHAR(64),
    MODEL VARCHAR(64),
    COLOR VARCHAR(64),
    PRIMARY KEY(BRAND, MODEL, COLOR),
    FOREIGN KEY(BRAND, MODEL) REFERENCES PADDLE --NEED ()?
);

CREATE TABLE GAME (
    GAME_NUM INT,
    TIMESTAMP DATETIME REFERENCES MATCH,
    F_PAD_BRAND VARCHAR(64),
    F_PAD_MODEL VARCHAR(64),
    S_PAD_BRAND VARCHAR(64),
    S_PAD_MODEL VARCHAR(64),
    F_PID INT REFERENCES PLAYER(ID) NOT NULL,
    S_PID INT REFERENCES PLAYER(ID) NOT NULL,
    F_EDGE INT,
    S_EDGE INT,
    F_TABLE_SIDE INT,
    F_SCORE INT NOT NULL,
    S_SCORE INT NOT NULL,
    BALL_BRAND VARCHAR(64),
    BALL_TIER INT,
    PRIMARY KEY(GAME_NUM, TIMESTAMP),
    FOREIGN KEY(F_PAD_BRAND, F_PAD_MODEL) REFERENCES PADDLE(BRAND, MODEL),
    FOREIGN KEY(S_PAD_BRAND, S_PAD_MODEL) REFERENCES PADDLE(BRAND, MODEL),
    FOREIGN KEY(BALL_BRAND, BALL_TIER) REFERENCES BALL(BRAND, TIER)
);

CREATE TABLE OWNS (
    PADDLE_BRAND VARCHAR(64),
    PADDLE_MODEL VARCHAR(64),
    PLAYER_ID int REFERENCES PLAYER(ID),
    PRIMARY KEY(PADDLE_BRAND, PADDLE_MODEL, PLAYER_ID),
    FOREIGN KEY(PADDLE_BRAND, PADDLE_MODEL) REFERENCES PADDLE(BRAND, MODEL)
);